name: Deploy Docker File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  approval:
    runs-on: self-hosted
    outputs:
      run_pipeline: ${{ steps.confirmation.outputs.run_pipeline }}
    steps:
      - name: Ask for Approval
        id: confirmation
        run: |
          echo "Do you want to run the deployment? (yes/no)"
          read input
          echo "Your input: $input"
          if [[ "$input" == "yes" ]]; then
            echo "run_pipeline=true" >> $GITHUB_OUTPUT
          else
            echo "run_pipeline=false" >> $GITHUB_OUTPUT
          fi
          echo "Approval Status: $input"

  build:
    needs: approval
    if: needs.approval.outputs.run_pipeline == 'true' # Run only if approved
    runs-on: self-hosted
    steps:
      - name: Build the Docker file
        run: sudo -E /home/ubuntu/deploy

