name: Deploy with Approval

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Approval before Deployment
        run: |
          echo "Do you want to proceed with the deployment? (yes/no)"
          read approval
          if [[ "$approval" != "yes" ]]; then
            echo "Deployment canceled by user."
            exit 1
          fi
          echo "Approval received. Proceeding with deployment."

      - name: Build and Deploy Docker File
        run: sudo -E /home/ubuntu/deploy

