name: Conditional Deploy Based on Flag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: ${{ vars.RUN_DEPLOYMENT == 'true' }}  # Check the flag value
    runs-on: self-hosted
    steps:
      - name: Check Deployment Flag
        run: |
          echo "Deployment flag is set to true. Proceeding with deployment."

      - name: Build and Deploy Docker File
        run: sudo -E /home/ubuntu/deploy

